### ISSUE TITLE
Is there a required ctype?

### ISSUE THREAD

**Issue by tyler-austin** [hobu/mgrs#19]
`
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgrs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\mgrs\__init__.py", line 1, in <module>
    from . core import rt
  File "C:\Python27\ArcGISx6410.6\lib\site-packages\mgrs\core.py", line 30, in <module>
    rt = ctypes.PyDLL(platform)
  File "C:\Python27\ArcGISx6410.6\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
`

**Comment by KevinNewCoding** [comment]
1 year later and I am getting this same issue. Any movement on this?

**Comment by hobu** [comment]
It awaits an investigation and patch to fix it. I do not have a Python 2.7 windows installation to do so, and with 2.7 going away as an officially supported version in December, it is unlikely I will undertake any such effort without direct funding.
