### ISSUE TITLE
Error converting 41RPR323901

### ISSUE THREAD

**Issue by wx1988** [hobu/mgrs#8]
>>> m.toLatLon('41RPR323901')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mgrs-1.3.1-py2.7-linux-x86_64.egg/mgrs/__init__.py", line 98, in toLatLon
    core.rt.Convert_MGRS_To_Geodetic( c, plat, plon)
  File "/usr/local/lib/python2.7/dist-packages/mgrs-1.3.1-py2.7-linux-x86_64.egg/mgrs/core.py", line 65, in check_error
    raise RTreeError(msg)
mgrs.core.RTreeError: Error in "Convert_MGRS_To_Geodetic": MGRS Errors

**Comment by hobu** [comment]
`m.toLatLon('41SPR3230090100')` works.
